addNewButton-AddForm-NoFUNCTIONALITY
ParmarManpreet/uturn-game pull request #55
Opened 2022-11-05 22:22 UTC by ParmarManpreet

- New button to generate Game URL
- Form that takes in the company name and expiration date(url)
![Screen Shot 2022-11-05 at 6 20 52 PM](https://user-images.githubusercontent.com/43555303/200143521-b6ccedd4-208e-4263-9bfc-7860f8f79da5.png)

2022-11-06 22:54 UTC, ParmarManpreet commented
Hey Ryan,

As I told you. Right now I can clikc Generate URL which creates the new URL within the Dialog.
That I need to figure out is when I click generate URL I need's to change the Dialog by now adding a "confirm/Submit" button
When this will be clicked then all information will be save in firebase
<img width="1000" alt="Screen Shot 2022-11-06 at 5 54 11 PM" src="https://user-images.githubusercontent.com/43555303/200199783-37d30320-6937-4296-8418-37f4719ea14a.png">

2022-11-12 02:16 UTC, RyanServera requested changes
Please review the comments and make the according changes

2022-11-12 02:16 UTC, RyanServera commented on src/components/dialogs/GameGenerateDialog.tsx
> +    //if date equal to today's date and time then prompt error to pick date in the future
No need to have validation, just set a minimum date on the date picker with the property minDate: https://mui.com/x/api/date-pickers/date-picker/

2022-11-12 02:16 UTC, RyanServera commented on src/components/dialogs/GameGenerateDialog.tsx
> +          <Button onClick={handleGenerate}>{props.translate('game-dialog-generate')}</Button>
Disable this button if your fields are empty with a function called `areGenerateFieldsEmpty` or something

2022-11-12 02:16 UTC, RyanServera commented on src/components/dialogs/GameGenerateDialog.tsx
> +    if(companyName !== '') {
not needed as the next suggestion will take care of validation

2022-11-12 02:16 UTC, RyanServera commented on src/pages/Admin.tsx
> +                        onSubmit={handleSubmit}
You don't need to have onSubmit because onSubmit is only if make use of data from the current page in the dialogue but in this case, you can save in the dialog itself

2022-11-12 02:16 UTC, RyanServera commented on src/pages/Admin.tsx
> +    }
not needed if you want to just close the dialog use the method`handleGameGenerationDialogClose`

2022-11-12 02:16 UTC, RyanServera commented on src/components/dialogs/GameGenerateDialog.tsx
> +  onSubmit: () => void
You can delete onSubmit because you are not manipulating or making use of data from the start page, all the data you will need is present in the dialog

2022-11-24 13:35 UTC, RyanServera commented
This PR was completed in https://github.com/ParmarManpreet/uturn-game/pull/65

2022-11-24 13:35 UTC, closed without merging